version: '3.3'
services:
  app:
    container_name: 'app'
    build: './'
    ports:
      - '8080:8080'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'