// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"modelo-graphql-go/internal/pkg/models"
)

type MutationResponse interface {
	IsMutationResponse()
}

type BookMutationResponse struct {
	Code    int          `json:"code"`
	Success bool         `json:"success"`
	Message string       `json:"message"`
	Book    *models.Book `json:"book"`
}

func (BookMutationResponse) IsMutationResponse() {}

type Health struct {
	Active bool `json:"active"`
}

type NewBook struct {
	Title    string `json:"title"`
	Author   string `json:"author"`
	Category int    `json:"category"`
}
