---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datalab-notification
  labels:
    app: datalab-notification
    version: v1
    tag: 1.0.0
    app.kubernetes.io/name: datalab-notification
    app.kubernetes.io/part-of: datalab-notification
    app.kubernetes.io/component: consumer
    app.kubernetes.io/instance: "datalab-notification-1.0.0"
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: datalab-notification
      version: v1
      tag: 1.0.0
  template:
    metadata:
      labels:
        app: datalab-notification
        version: v1
        tag: 1.0.0
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: datalab-notification
          image: rennerdigital.azurecr.io/purchasing/datalab-notification:1.0.0
          imagePullPolicy: Always
          env:
            - valueFrom:
                configMapKeyRef:
                  key: MONGODB_PASSWORD
                  name:  purchase-request-config
              name:  MONGODB_PASSWORD
            - valueFrom:
                  configMapKeyRef:
                    key: GIN_MODE
                    name:  purchase-request-config
              name: GIN_MODE
          volumeMounts:
            - mountPath: /app/configs/
              name: application-config
          resources:
            limits:
              cpu: "0.5"
              memory: 0.5G
            requests:
              cpu: "0.1"
              memory: 0.1G
#          livenessProbe:
#            httpGet:
#              path: /healthz
#              port: 8080
#            initialDelaySeconds: 10
#            periodSeconds: 5
#          readinessProbe:
#            httpGet:
#              path: /healthz
#              port: 8080
#            initialDelaySeconds: 10
#            periodSeconds: 5
      volumes:
        - name:  application-config
          configMap:
            name: datalab-notification-config
            items:
              - key: application.yml
                path:  application.yml